---
  - name: upgrade and  update packages
    become: true
    apt: 
     update_cache: yes
   
  - name: "install the dependencies."
    become: true
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes

  - name: "install pm2"
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: present
  
  - name: copy backend
    copy:
      src: /root/project/artifact.tar.gz
      dest: /home/ubuntu/artifact.tar.gz

  - name: unzip Backend
    shell: |
      cd /home/ubuntu
      tar xvzf artifact.tar.gz -C .
      ls -la
      
  - name: Build
    become: true
    shell: |
      cd /home/ubuntu
      npm install
      npm run build
      
  - name: Start PM2
    shell: |
      cd /home/ubuntu
      pm2 start npm --name backend -- start

#   - name: install ans start app
#     command:  pm2 start main.js
#     args:
#       chdir: ~/backend/dist
